security:

    providers:

        app_user_provider:
            entity:
                class: App\Entity\User
                property: email


    encoders:
        App\Entity\User:
            algorithm: bcrypt

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000

    access_control:
